### ISSUE TITLE
Add Sys.sleep to the `map` command ?

### ISSUE THREAD

**Issue by matiasandina** [jennybc/send-email-with-r#15]
The walk-through works like a charm but I got into "rate limit" problems. 
I tried to modify it like this 

```
safe_send_message <- function(){
Sys.sleep(0.1)
safely(send_message)
}
```
But did not work as expected. How can we add some sort of delay to prevent getting into the rate limit (not trying to spam thousands of people, got this issue with < 50)?

**Comment by jennybc** [comment]
It needs to look more like this:

``` r
slowly <- function(f, delay = 0.5) {
  function(...) {
    Sys.sleep(delay)
    f(...)
  }
}
safe_slow_send_message <- slowly(safely(send_message))
sent_mail <- emails %>%
  pmap(mime) %>%
  map(safe_slow_send_message)
```

But since I last did this sort of thing, purrr has gained several helpful functions. So I actually recommend that you try that first, before rolling your own.

https://www.tidyverse.org/articles/2019/02/purrr-0-3-0/
(see the stuff re: "A new set of tools helps limiting the rate at which a function is called ...")
